export { default as L1_Q1 } from './question1';
export { default as L1_Q2} from './question2';
export { default as L1_Q3 } from './question3';
export { default as L1_Q4} from './question4';
export { default as L1_Q5 } from './question5';
export { default as L1_Q6} from './question6';
export { default as L1_Q7 } from './question7';
export { default as L1_Q8} from './question8';
export { default as L1_Q9 } from './question9';
export { default as L1_Q10} from './question10';